spring:
  application:
    name: EurekaServer

server:
  port: 7070

eureka:
  password: password
  instance:
    hostname: 192.168.1.112
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    leaseRenewalIntervalInSeconds: 10
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/